#!/bin/bash
#
# Provides:                 backup-user
# Short-Description:        export current user paths to backup path
# Description:              export current user paths to backup path

######################## GLOBAL FUNCTIONS
#S_TRACE=debug

S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1

########################  DATA

# paths to compress
declare -A pths_comp
# paths to exclude of pths_comp
declare -A pths_comp_exc
# paths to compress
declare -A pths_sync
# paths to exclude of pths_sync
declare -A pths_sync_exc

pth_backup_base="/ext/backups"

# COMPRESS: sub level to compress
pths_comp["/"]="etc"
pths_comp["/home"]="${USER}" # option 'all' take all /home subdirectories
pths_comp["${HOME}"]=".config
.eclipse
.FreeCAD
.squirrel-sql
.ssh
.sublime-project
.tmux
.webclipse" # .gitkraken

#pths_comp["/home/shared"]=".aMule Desktop dev Documents Downloads .gse-radio Help kdenlive keep .local .perso Pictures Public .rsync .themes Work www"
pths_comp["/home/shared"]="*"
pths_comp["/opt"]="*" # option 'all' take all /opt subdirectories

pths_comp_exc["/home/shared"]=".torrent
Archives
Downloads
Class
Cnam
Mooc
tmp
virtualbox
vmware"

# SYNC: sub level to synchronize
#pths_sync["/var/lib/libvirt"]="export"
pths_sync["/var/lib/lxd"]="export"

tar_opt=" --exclude='.cache' -czf"
tar_ext="tar.gz"
sync_opt="-av --delete --exclude=.snapshots --exclude=.cache"

ddate=$(date +%Y%m%d)

# define desktop environment
[ -d "/etc/xdg/xfce4" ] && env="xfce"
[ -d "/etc/gdm" ] && env="gnome"

if [ -z "$env" ]; then
	pth_backup=${pth_backup_base}/${HOST}/export-${HOST}-${USER}-${S_RELEASE_NAME}-${ddate}
else
	pth_backup=${pth_backup_base}/${HOST}/export-${HOST}-${USER}-${S_RELEASE_NAME}-${env}-${ddate}
fi


########################  FUNCTION

_compress() {
	local pth

	_echoT "======> compress from $1"

	# create pth_to
	pth_to="${pth_backup}/${1##*/}"
	pth_to="${pth_to%/}"
	if ! [ -d "${pth_to}" ]; then
		mkdir -p "${pth_to}" || _exite "unable to create directory '${pth_to}'"
	fi

	# define subpaths
	cd "$1"
	if [ "${pths_comp[$1]}" = "*" ]; then
		pths="$(ls -I. -I.. -a1)"
	else
		pths="${pths_comp[$1]}"
	fi

	while read pth; do
		if [ -e "${pth}" ]; then
			# step excluding paths
			if [[ ${pths_comp_exc["$1"]} = *${pth}* ]]; then
				#echo "exclude ${pth}"
				continue
			fi

			echo "=> ${pth}"
			file_to="${pth_to}/${pth}.${tar_ext}"
			[ -e "$file_to" ] && _echoa "warning - overwrite file $file_to"
			cmd="sudo tar ${tar_opt} '$file_to' '${pth}'"
			eval $cmd || _exite "executing '$cmd'"
			sudo chown ${USER}:${USER} "${file_to}"
		else
			_echoa "warning - skipped, unable to find '${1}/${pth%/}'"
		fi
	done <<< ${pths}
}

_rsync() {
	_echoT "------> sync from $1"

	# create pth_to
	pth_to="${pth_backup}/${1##*/}"
	pth_to="${pth_to%/}"
	if ! [ -d "${pth_to}" ]; then
		mkdir -p "${pth_to}" || _exite "unable to create directory '${pth_to}'"
	fi

	# define subpaths
	if [ "${pths_sync[$1]}" = "*" ]; then
		pths="$(ls -I. -I.. -a1)"
	else
		pths="${pths_sync[$1]}"
	fi

	while read pth; do
		if [ -e "${pth_to}}/${pth}" ]; then
			# step excluding paths
			if [[ ${pths_sync_exc["$1"]} = *${pth}* ]]; then
				#echo "exclude ${pth}"
				continue
			fi

			echo "-> ${pth}"
			cmd="sudo rsync $sync_opt '${1}/${pth%/}/' '${pth_to}/${pth%/}/'"
			eval $cmd || _exite "while executing '$cmd'"
		else
			_echoa "warning - skipped, unable to find '${1}/${pth%/}'"
		fi
	done <<< ${pths}
}


########################  MAIN


_echoT "########################
EXPORT to ${pth_backup}\n"

if ! [ -d "${pth_backup}" ]; then
	(sudo mkdir -p ${pth_backup} && sudo chown ${USER}:${USER} ${pth_backup}) || _exite "unable to create/modify rights to directory '${pth_backup}'"
fi


# CLEAN
_echoT "------------------ clean"
#pth=~/.cache && [ -d ${pth} ] && rm -fR ${pth}/*
pth=~/.local/share/Trash
[ -d ${pth} ] && sudo rm -fR ${pth}
# find trashes
sudo find / -not \( -regex "\(/proc\|/sys\|/run/user\)" -prune \) -not -type p -name .Trash* -exec sudo rm -fR "{}" \;


_echoT "------------------ compress"

# COMP EXE
for pth_comp in ${!pths_comp[*]}; do
	if [ -e "$pth_comp" ]; then
		_compress "$pth_comp" "${pths_comp[$pth_comp]}"
	else
		_echoa "warning - skipped unable to find '$pth_comp'"
	fi
done

# COMP POST


_echoT "------------------ synchronize"

<<KEEP
# SYNC PRE
if [ "$(ls /var/lib/libvirt/)" ]; then
	_echoT "------------------ KVM"
	_echoT "- rights"
	${pth_cmd}/kvm-rights

	_echoT "- export"
	${pth_cmd}/kvm-export
	_echoT "------------------ END"
fi
KEEP

# SYNC EXE
for pth_sync in ${!pths_sync[*]}; do
	if [ -e "$pth_sync" ]; then
		_rsync "$pth_sync" "${pths_sync[$pth_sync]}"
	else
		_exite "warning - skipped unable to find '$pth_comp'"
	fi
done

# SYNC POST

_echoT "END
########################"


