#!/bin/bash
#
# Provides:						backup-soft
# Short-Description:		backup / restore selected and installed softwares in /opt
# Description:					backup / restore selected and installed softwares in /opt

######################## GLOBAL FUNCTIONS
S_TRACE=debug

S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1

########################  VARIABLES

declare USAGE="backup-soft : backup softwares from /opt
Available softwares:
    archimate architect eclipse_java eclipse_tools mindmaster pipe
    smartgit squirrel-sql sublime_merge sublime_text workcraft yed
    zotero

Global usage:
backup-soft <args> <softwares>...
backup-soft <args> [-r|--restore [<date>]] <softwares>...
backup-soft <args> [-v|--version <version>] -r|--restore [<date>] <softwares>...

softwares:
	a list of 'nominal' software names
	if given, desactive option 'all'

args:
	-m,--menu		select options by menu
	-a,--all		select all softwares
	-f, --force         	delete existing files before restore
	-r, --restore [<date>]	backup date of softwares in format : '+%Y%m%d-%s'
	-v, --version       	add given version to backup/restore

	-h, --help		show usage of functions
	-q, --quiet		don't show any infomations except interaction informations
	-d, --debug		output in screen & in file debug informations
"

########################  FUNCTION

# initialize default paths to backup
__init() {
	local theme

	[ -d "${_PATH_BACKUP}" ] || _exite "Unable to find path: ${_PATH_BACKUP}"

	# connectors
	PATHS_SOFT["connectors"]="pth_user=${HOME}
comp_pth_opt=/opt/connectors"

	# archimate
	PATHS_SOFT[architect]="pth_user=${HOME}
comp_pth_opt=/opt/archimate
comp_pth_conf=${HOME}/.archimate
comp_pth_user=${HOME}/dev/archimate
comp_file_desk=${HOME}/.local/share/applications/archimate.desktop
comp_file_bin=/usr/local/bin/archimate"

	# architect
	PATHS_SOFT[architect]="pth_user=${HOME}
comp_pth_opt=/opt/architect
comp_pth_conf=${HOME}/.architect
comp_pth_user=${HOME}/dev/architect
comp_file_desk=${HOME}/.local/share/applications/architect.desktop
comp_file_bin=/usr/local/bin/architect"

	# eclipse
	for theme in java tools; do
		PATHS_SOFT[eclipse_${theme}]="pth_user=${HOME}
comp_pth_opt=/opt/eclipse_${theme}
comp_pth_conf=${HOME}/.eclipse_${theme}
comp_pth_user=${HOME}/dev/eclipse-workspaces-${theme}
comp_file_desk=${HOME}/.local/share/applications/eclipse_${theme}.desktop
comp_file_bin=/usr/local/bin/eclipse_${theme}"
	done

	# mindmaster
	PATHS_SOFT[mindmaster]="pth_user=${HOME}
comp_pth_opt=/opt/mindmaster
comp_pth_conf=${HOME}/Edraw/MindMaster
comp_file_desk=${HOME}/.local/share/applications/mindmaster.desktop
comp_file_bin=/usr/local/bin/mindmaster"

	# pipe
	PATHS_SOFT[pipe]="pth_user=${HOME}
comp_pth_opt=/opt/pipe
comp_file_desk=${HOME}/.local/share/applications/pipe.desktop
comp_file_bin=/usr/local/bin/pipe"

	# smargit
	PATHS_SOFT[smartgit]="pth_user=${HOME}
comp_pth_opt=/opt/smartgit
comp_pth_conf=${HOME}/.config/smartgit
comp_file_desk=${HOME}/.local/share/applications/smartgit.desktop
comp_file_bin=/usr/local/bin/smartgit"

	# squirrel-sql
	PATHS_SOFT[squirrel-sql]="pth_user=${HOME}
comp_pth_opt=/opt/squirrel-sql
comp_pth_conf=${HOME}/.squirrel-sql
comp_file_desk=${HOME}/.local/share/applications/squirrel-sql.desktop
comp_file_bin=/usr/local/bin/squirrel-sql"

	# sublime-merge
	PATHS_SOFT[sublime_merge]="pth_user=${HOME}
comp_pth_opt=/opt/sublime_merge
comp_pth_conf=${HOME}/.config/sublime-merge
comp_file_desk=${HOME}/.local/share/applications/sublime-merge.desktop
comp_file_icon=${HOME}/.local/share/icons/sublime-merge.png
comp_file_bin=/usr/local/bin/sublime_merge"

	# sublime-text
	PATHS_SOFT[sublime_text]="pth_user=${HOME}
comp_pth_opt=/opt/sublime_text
comp_pth_conf=${HOME}/.config/sublime-text
comp_pth_user=${HOME}/.sublime-project
comp_file_desk=${HOME}/.local/share/applications/sublime-text.desktop
comp_file_icon=${HOME}/.local/share/icons/sublime-text.png
comp_file_bin=/usr/local/bin/sublime_text"

	# workcraft
	PATHS_SOFT[workcraft]="pth_user=${HOME}
comp_pth_opt=/opt/workcraft
comp_pth_conf=${HOME}/.config/workcraft
comp_file_desk=${HOME}/.local/share/applications/workcraft.desktop
comp_file_bin=/usr/local/bin/workcraft"

	# yed
	PATHS_SOFT[yed]="pth_user=${HOME}
comp_pth_opt=/opt/yed
comp_pth_conf=${HOME}/.yEd
comp_file_desk=${HOME}/.local/share/applications/yed.desktop
comp_file_bin=/usr/local/bin/yed"

	# zotero
	PATHS_SOFT[zotero]="pth_user=${HOME}
comp_pth_opt=/opt/zotero
comp_pth_conf=${HOME}/.zotero
comp_pth_user=/home/shared/Zotero
comp_file_desk=${HOME}/.local/share/applications/zotero.desktop
comp_file_bin=/usr/local/bin/zotero"

	#_echod "${FUNCNAME}::${LINENO} \${!PATHS_SOFT[@]}=${!PATHS_SOFT[@]}"
	#_echod "${FUNCNAME}::${LINENO} \${PATHS_SOFT[@]}=${PATHS_SOFT[@]}"
}

__menu() {
	local comp_pth_opt comp_pth_conf comp_file_desk comp_file_bin

	_menu "Select an action" backup restore
	_ACTION=${_ANSWER}

	_menu "Select a software to backup" $(echo ${!PATHS_SOFT[@]}|tr ' ' '\n'|sort)
	_SOFTS=${_ANSWER}

	# set variables in "${PATHS_SOFT["${software}"]}"
	eval "${PATHS_SOFT[${_SOFTS}]}"
	if [ "${_ACTION}" = restore ]; then
		_menu "Select an action" $(ls -1r ${_PATH_BACKUP}|sed -n "s|^${_SOFTS}_\([0-9-]\+\)\.tar\.gz$|\1|p")
		_DATEB=${_ANSWER}
	fi
}

# $1 list of softwares
__backup() {
	_echod "${FUNCNAME}::${LINENO} \$1=$1"

	local software name

	# COMP PRE
	_echoT "BACKUP start"

	# COMP EXE
	for software in $1; do
		_echod "${FUNCNAME}::${LINENO} \$software=${software}"
		_echod "${FUNCNAME}::${LINENO} \${!PATHS_SOFT[@]}=${!PATHS_SOFT[@]}"

		if [ "${PATHS_SOFT[${software}]}" ]; then
			__backup_one "${software}" "${PATHS_SOFT[${software}]}"
		else
			_echoE "backup skipped: unable to find '${software}' in existing softwares configuration"
		fi
	done

	# COMP POST
	_echoT "BACKUP end"
}

# $1 software
# $2 string of paths definitions
__backup_one() {
	_echod "${FUNCNAME}::${LINENO} \$1=$1"
	_echod "${FUNCNAME}::${LINENO} \$2=$2"

	local pth pths_comp
	local comp_pth_opt comp_pth_conf comp_file_desk comp_file_bin

	_echot "backup '$1' -->"

	# set variables in "${PATHS_SOFT["${software}"]}"
	eval "$2"
	pths_comp=`echo "${PATHS_SOFT["$1"]}"|sed -n 's|^comp_.*=\(.*\)$|\1|p'|xargs`
	if [ -z "${comp_pth_opt}" ]; then
		_echoE "backup skipped for '$1': 'comp_pth_opt' is empty"
		return 1
	fi

	# check if pths_comp exists
	for pth in ${pths_comp}; do
		if [ ! -e "${pth}" ]; then
			_echoE "'$1' skipped: missing path '${pth}'"
			return 1
		fi
	done

	version=${VERSION:+-${VERSION}}
	name=${_PATH_BACKUP}/$1${version}_${DATE}.${COMP_EXT}
	cmd="${COMP_CMD} '${name}' ${pths_comp} 2>&6"
	_eval ${cmd} || _echoE "executing '${cmd}'"

	_echot "--> '${name}'"
}

# $1 list of softwares
__restore() {
	_echod "${FUNCNAME}::${LINENO} \$1=$1"

	local software

	# UNCOMP PRE
	_echot "RESTORE start"

	# UNCOMP EXE
	for software in $1; do
		_echod "${FUNCNAME}::${LINENO} \$software=${software}"
		_echod "${FUNCNAME}::${LINENO} \${!PATHS_SOFT[@]}=${!PATHS_SOFT[@]}"

		if [ "${PATHS_SOFT["${software}"]}" ]; then
			__restore_one "${software}" "${PATHS_SOFT["${software}"]}"
		else
			_echoE "restore skipped: unable to find '${software}' in existing softwares configuration"
		fi
	done

	# UNCOMP POST
	_echot "RESTORE end"
}

# $1 software
# $2 string of paths definitions
__restore_one() {
	_echod "${FUNCNAME}::${LINENO} \$1=$1"
	_echod "${FUNCNAME}::${LINENO} \$2=$2"

	local pths_comp pth pth_from pth_to file_back
	local comp_pth_opt comp_pth_conf comp_file_desk comp_file_bin

	# set variables in "${PATHS_SOFT["${software}"]}"
	eval "$2"
	version=${VERSION:+-${VERSION}}

	file_back=`ls "${_PATH_BACKUP}/$1${version}_${_DATEB}.${COMP_EXT}"`
	# file not found
	if ! ls "${file_back}" 1>/dev/null 2>&1; then
		_echoE "'$1' skipped: unable to find '${file_back}'"
		return 1
	fi

	_echod "${FUNCNAME}::${LINENO} \$_DATEB=${_DATEB}"
	# existing paths
	pths_comp=`echo "${PATHS_SOFT["$1"]}"|sed -n 's|^comp_.*=\(.*\)$|\1|p'|xargs`
	# check if pths_comp exists
	for pth in ${pths_comp}; do
		if [ -e "${pth}" ]; then
			if [ -z "${FORCE}" ]; then
				_echoE "'$1' skipped: path exists '${pth}', to delete it use option '--force'"
				return 1
			else
				[ -w "${pth}" ] && cmd="sudo rm -fR '${pth}'"
				_eval ${cmd} || _echoE "executing '${cmd}'"
			fi
		fi
	done

	# delete temporary path
	pth_tmp="/tmp/backup-${DATE}"
	[ -d '${pth_tmp}' ] && rm -fR "${pth_tmp}"
	mkdir -p "${pth_tmp}"

	cmd="${UNCOMP_CMD} '${file_back}' -C '${pth_tmp}' 2>&6"
	_eval ${cmd} || _echoE "executing '${cmd}'"
	for pth in ${pths_comp}; do
		pth_from=${pth_tmp}/${pth#/}
		pth_to=${pth%/}
		cmd="sudo mv '${pth_from}' '${pth_to}'"
		_eval ${cmd} || _echoE "executing '${cmd}'"
	done
}

__opts() {
	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"

	local opts_given="$@"
	local opts_short="aflmr:v:hdq"
	local opts_long="all,force,list,menu,restore:,version:,help,quiet,debug"
	local opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@") || _exite "Wrong or missing options"
	eval set -- "${opts}" || exit 1

	_echod "${FUNCNAME}::${LINENO} opts_given=${opts_given} opts=${opts}"
	while [ "$1" != "--" ]
	do
		case "$1" in
			-a|--all)
				_SOFTS="${!PATHS_SOFT[@]}"
				;;
			-f|--force)	
				FORCE="force"
				;;
			-r|--restore)
				shift
				_ACTION=restore
				_DATEB="$1"
				;;
			-m|--menu)
				MENU="menu"
				;;
			-v|--version)
				shift
				VERSION="$1"
				;;
			-l|--list)
				echo ${!PATHS_SOFT[@]}
				_exit 0
				;;
			-h|--help)
				echo "${USAGE}"
				_exit 0
				;;
			-d|--debug)	
				_redirect debug
				;;
			*)	
				_exite "Wrong argument: '$1' for arguments '$opts_given'"
				;;
		esac
		shift
	done

	shift
	[ "$*" ] && _SOFTS="$@"

	# menu
	[ "${MENU}" ] && __menu
	# no softwares
	[ -z "${_SOFTS}" ] && _exite "You have to give softwares or the option 'all'"
	# default action
	[ -z "${_ACTION}" ] && _ACTION=backup

	_echod "${FUNCNAME}::${LINENO} MENU='${MENU}' FORCE='${FORCE}' REGEXP='${REGEXP}' "
	_echod "${FUNCNAME}::${LINENO} _ACTION='${_ACTION}' _SOFTS='${_SOFTS}' _DATEB='${_DATEB}'"
}

__main() {
	_echod "======================================================"
	_echod "$(ps -o args= ${PPID})"

	local _PATH_BACKUP _DATEB _ACTION _SOFTS

	# array for softwares definition
	declare -A PATHS_SOFT
	# path to backup/resore
	[ -d ${HOME}/Soft/multi ] && _PATH_BACKUP=${HOME}/Soft/linux/backup || _PATH_BACKUP=/ext/shared/Soft/linux/backup
	# date for files
	local DATE=`date +%Y%m%d-%s`
	# compress command options
	local COMP_CMD="tar --exclude='.cache' -czf"
	local UNCOMP_CMD="tar -xzf"
	local COMP_EXT="tar.gz"

	# initialize variables for each softwares
	__init

	# get options
	__opts "$@"

	# call action with arguments
	__${_ACTION} "${_SOFTS}"
}

########################  MAIN

__main "$@"
_exit 0
