#!/bin/bash
#
# Provides:             haconf
# Short-Description:    control extended configurations files for haproxy
# Description:          control extended configurations files for haproxy

################################ GLOBAL FUNCTIONS
#S_TRACE=debug

S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
! . "$S_GLOBAL_FUNCTIONS" && echo -e "[error] - Unable to source file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'" && exit 1

################################  VARIABLES

usage="haconf, control extended configurations files for haproxy
haconf -h, --help

For the optionnal arguments NAME, you can use the wildcard for the name
	or alone for all selection.
	without agument NAME command return a global selection without filter.

options:
    -h, --help			print usage of this command
    -q, --quiet		Don't show any infomations except errors
    -d, --debug		output debugging in screen & file

	check				check all the enabled configuration files
	reload				reload the haproxy daemon

    clear						clear all broken links of configurations
    list <names>			return a list of 'enabled / disabled / broken' configurations
    enable <names>	enable disabled configuration names
    								& print a list of 'enabled / enable' configurations
    disable <names>	disable an enabled configuration
    								& print a list of 'disabled / enable' configurations
    <names> are an expansion format
"

################################  FUNCTION

# check enabled configuration files
__check() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local confs conf

	for conf in $(ls "${path_enabled}/*" 2>/dev/null); do
		configs=" $configs -f $conf"
	done;

	haproxy -c -f /etc/haproxy/haproxy.cfg $configs >/dev/null && _echo 'OK' || _echoE 'KO'
}

# clear broken links for names of available configuration
__clear() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local confs

	confs="$(find -L ${path_enabled}/ -type l|sort|sed "s|${path_enabled}/||")"
	_evalq "find -L ${path_enabled}/ -type l -exec rm {} \\;"

	[ "$confs" ] && _echo "The following broken links are deleted:\n$confs"
}

__print() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local conf enabled disabled

	# enabled
	enabled="$(find -L ${path_enabled}/ -type f|sort|sed "s|${path_enabled}/||")"

	# disabled
	disabled="$(ls "${path_available}")"
    for conf in $enabled; do
    	disabled="${disabled/$conf}"
    done
	disabled="$(echo -e "$disabled"|sort -u|sed '/^$/d')"
	_echoD "${FUNCNAME}():$LINENO enabled=$enabled"
	_echoD "${FUNCNAME}():$LINENO disabled=$disabled"

	paste <(echo -e "--${1}--\n$ok") <(echo -e "--enabled--\n$enabled") <(echo -e "--disabled--\n$disabled")|column -tn
	[ "$ok" ] && echo -e "\nTo activate the new configuration, use 'haconf reload'"
}

# 1 path to list
# s-@ names to search
__get_confs() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local path confs conf
	path="$1"
	shift
	_echoD "${FUNCNAME}():$LINENO path=${path} \$@=$@"

	# list confs
	for conf in $@; do
		confs="${confs}
$(ls -1 "${path}"/${conf} 2>/dev/null)"
	done
	echo -e "$confs"|sort -u|sed "s|${path}/||"|xargs
}

# enable configuration files with his short names (without extension)
# $* : configuration names
__enable() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local conf confs enabled ok ko

	confs="$(__get_confs "${path_available}" "$@")"
	_echoD "${FUNCNAME}():$LINENO confs="${confs}

	# select confs
	for conf in ${confs}; do
	    [ -h "${path_enabled}/${conf}" ]  && _evalq rm "${path_enabled}/${conf}"
	    _evalq ln -s ${path_available}/${conf} ${path_enabled}/${conf}
	    ok="$ok${conf}\n"
	done

	__print "enable"
}

# disable configuration files with his short names (without extension)
# $* : configuration names
__disable() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local conf confs enabled ok ko

	confs="$(__get_confs "${path_available}" "$@")"
	_echoD "${FUNCNAME}():$LINENO confs="${confs}

	# select confs
	for conf in $confs; do
		if [ -h "${path_enabled}/${conf}" ]; then
			_evalq rm ${path_enabled}/${conf}
			ok="$ok${conf}\n"
		fi
	done

	__print "disable"
}

# print list names of available configuration
__list() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	local enabled disabled ko conf

	# select confs
	if [ -z $@ ]; then
		disabled="$(ls "${path_available}")"
		enabled="$(find -L "${path_enabled}"/ -type f|sort|sed "s|${path_enabled}/||")"
		ko="$(find -L "${path_enabled}"/ -type l|sort|sed "s|${path_enabled}/||")"
	else
		# select confs
		for conf in $@; do
			disabled="${disabled}
$(find ${path_available}/ -type f -name ${conf}|sort|sed "s|${path_available}/||")"
			enabled="${enabled}
$(find -L ${path_enabled}/ -type f -name ${conf}|sort|sed "s|${path_enabled}/||")"
			ko="${ko}
$(find -L ${path_enabled}/ -type l -name ${conf}|sort|sed "s|${path_enabled}/||")"
		done
	fi

	# disabled
    for conf in $enabled; do
    	disabled="${disabled/$conf}"
    done
	disabled="$(echo -e "$disabled"|sort -u|sed '/^$/d')"
	enabled="$(echo -e "$enabled"|sort -u|sed '/^$/d')"
	ko="$(echo -e "$ko"|sort -u|sed '/^$/d')"

	if [ "$ko" ]; then
		paste <(echo -e "--enabled--\n$enabled") <(echo -e "--disabled--\n$disabled") <(echo -e "--broken--\n$ko")|column -tn
	else
		paste <(echo -e "--enabled--\n$enabled") <(echo -e "--disabled--\n$disabled")|column -tn
	fi
	[ "$ko" ] && echo -e "\nTo clean broken links, use: 'haconf clear'"
}

# reload haproxy daemon
__reload() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	_service reload haproxy && _echo "haproxy have been reloaded" || _echoE "error, something wrong"
}

__opts() {
	_echoD "${FUNCNAME}():$LINENO IN \$@=$@"

	opts_given="$@"
	opts_short="hdq"
	opts_long="help,debug,quiet"
	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@")
	eval set -- "${opts}"

	_echoD "${FUNCNAME}():$LINENO opts_given=$opts_given opts=$opts"
	while [ "$1" != "--" ]
	do
		case "$1" in
			--help)
				echo "$usage"
				;;
			-q|--quiet)
				_redirect quiet
				;;
			-d|--debug)
				_redirect debug
				;;
			*)
				_exite "Wrong argument: '$1' for arguments '$opts_given'"
				;;
		esac
		shift
	done

	shift
	action="$1"
	shift
	opts="$@"
	_echoD "${FUNCNAME}():$LINENO action='$action' opts='$opts'"
}

__main() {
	_echod "---------------------------------------------------------------------"
	_echod "$0 ${FUNCNAME}()"

	! type haproxy &>/dev/null && _exite "Haproxy are not installed !"

	local opts_given opts_short opts_long opts
	local confs conf regexp path
	local path_enabled="/etc/haproxy/conf-enabled"
	local path_available="/etc/haproxy/conf-available"

	for path in "$path_enabled" "$path_available"; do
		! [ -d "$path" ] && mkdir -p "$path"
	done

	__opts "$@"

	[ -z "$action" ] && _exite "You have to give an action to execute"
	if [[ " check clear enable disable list reload " = *" $action "* ]]; then
		# call action with arguments
		__$action "${opts}"
	else
		_exite "Wrong action: '$action'. select in: check clear enable disable list reload"
	fi
}

################################  MAIN

__main "$@"

_exit 0
