#!/bin/bash
#
# Provides:                 rsync-server
# Short-Description:        use rsync to specific usage
# Description:              use rsync to specific usage

################################ GLOBAL FUNCTIONS
#S_TRACE=debug

! [[ "$S_GLOBAL_FUNCTIONS" && -f $S_GLOBAL_FUNCTIONS ]] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
. $S_GLOBAL_FUNCTIONS

################################  FUNCTION

__ip_name() {
	local ip name

	name=${1%:*}
	name=${name#*@}
	[ -n "$name" ] && ip=$(grep "$name" /etc/hosts | cut -f1)
	echo ${ip:-$name}
}
__port_name() {
	local port name

	name=${1%:*}
	name=${name#*@}
	[ -n "$name" ] && id=$(grep "$name" /etc/hosts | cut -f2)
	[ "$id" ] && port=`sed -n 's|.*port=\([^ ]\+\).*|\1|p' <<<${S_CLUSTER[$id]}`
	echo ${port:+"-e 'ssh -p $port' "}
}
__rsync() {
	_echoD "$FUNCNAME:$LINENO cmd='${cmd}' from='${from}' to='${to}' exclude='${exclude}' excludefrom='${excludefrom}'"
	_echoD "$FUNCNAME:$LINENO _IPTHIS='${_IPTHIS}' include='${include}' includefrom='${includefrom}'"
	_echoD "$FUNCNAME:$LINENO delete='${delete}' dryrun='${dryrun}' archive='${archive}' verbose='${verbose}'"

	_opts="${opts}${archive}${verbose}${dryrun}" && _opts=${_opts:+" -$_opts"}

	_delete=${delete:+" --delete"}

	ip_from=$(__ip_name ${from})
	ip_to=$(__ip_name ${to})
	# check origin
	[ "${ip_from}" = "${_IPTHIS}" ] && ! [ "${force}" ] && _askyn "This IP is the same as the origin, please confirm" && [ "$_ANSWER" = "n" ] && exit 1
	# check destination
	[ "${ip_to}" = "${_IPTHIS}" ] && ! [ "${force}" ] && _askyn "This IP is the same as the destination, please confirm" && [ "$_ANSWER" = "n" ] && exit 1

	for str in ${exclude}; do _exclude+=" --exclude=\"${str}\""; done
	for str in ${excludefrom}; do _excludefrom+=" --exclude-from=\"${str}\""; done
	for str in ${include}; do _include+=" --include=\"${str}\""; done
	for str in ${includefrom}; do _includefrom+=" --include-from=\"${str}\""; done

	#for str in ${exclude}; do _exclude+=" "
	_eval "rsync${_opts}${_delete}${_exclude}${_excludefrom}${_include}${_includefrom} $(__port_name ${from})${from} $(__port_name ${to})${to}"
}

################################  VARIABLES

usage="rsync-server : function over rsync to specific usage
rsync-server --help

vzl [options] [ctids / all]
	ctids is a list combinating simple ids of containers and range. ex : '100 200-210'

	-a, --archive        archive mode; equals -rlptgoD (no -H,-A,-X)
	-v, --verbose        increase verbosity
	-n, --dry-run        perform a trial run with no changes made
	--delete             delete extraneous files from destination dirs
	--exclude PATTERN    exclude files matching PATTERN
	--exclude-from FILE  read exclude patterns from FILE
	--include PATTERN    don't exclude files matching PATTERN
	--include-from FILE  read include patterns from FILE

	-f, --force          don't ask confirmation (example: destination & origin IPs are the same)
	-d, --debug          output in screen & in file debug informations
"

################################  MAIN

# OUT: no options given
! [ "$*" ] && _echoE "no options given" && exit 1

cmd="__rsync"
bin_exclude="/usr/local/bs/conf/rs-bin.exc"
install_exclude="/usr/local/bs/conf/rs-install.exc"

optsgiven="$@"
optsshort="dafnvrlptogD"
optslong="help,debug,archive,force,dry-run,verbose,delete,exclude:,exclude-from:,include:,include-from:"
opts=$(getopt -o ${optsshort} -l ${optslong} -n "${0##*/}" -- "$@" 2>/tmp/${0##*/}) || _exitE "$(</tmp/${0##*/})'"
eval set -- "${opts}"
opts=

# options
_echoD "$FUNCNAME:$LINENO optsgiven='${optsgiven}' opts='${opts}'"
while true; do
	case "$1" in
		--help)
			_echo "$usage"; _exit
			;;
		-d|--debug)
			_redirect debug
			;;
		-a|--archive)
			archive="a"
			;;
		-f|--force)
			force="f"
			;;
		-n|--dry-run)
			dryrun="n"
			;;
		-v|--verbose)
			verbose="v"
			;;
		--delete)
			delete="delete"
			;;
		--exclude)
			shift
			exclude+=" $1"
			;;
		--exclude-from)
			shift
			excludefrom+=" $1"
			;;
		--include)
			shift
			include+=" $1"
			;;
		--include-from)
			shift
			includefrom+=" $1"
			;;
		-r|--recursive)
			opts+="r"
			;;
		-l|--links)
			opts+="l"
			;;
		-p|--perms)
			opts+="p"
			;;
		-t|--times)
			opts+="t"
			;;
		-o|--owner)
			opts+="o"
			;;
		-g|--group)
			opts+="g"
			;;
		-D)
			opts+="D"
			;;
		--)
			shift
			break
			;;
		*)
			_exitE "Bad options: '$1' in '${optsgiven}'"
			;;
	esac
	shift
done

_echoD "$FUNCNAME:$LINENO \$*='$*'"
case "$1" in
	# dev
	ddn1|dev-desktop-node1)
		from="/home/shared/dev/"
		to="root@node1:/save/sync/dev/"
		;;
	dn1d|dev-node1-desktop)
		from="root@node1:/save/sync/dev/"
		to="/home/shared/dev/"
		;;
	ddn2|dev-desktop-node2)
		from="/home/shared/dev/"
		to="root@node2:/save/sync/dev/"
		;;
	dn2d|dev-node2-desktop)
		from="root@node2:/save/sync/dev/"
		to="/home/shared/dev/"
		;;
	# install server
	idn1|install-desktop-node1)
		from="/home/shared/dev/install/"
		to="root@node1:/usr/local/bs/install/"
		excludefrom+="${install_exclude}"
		;;
	in1d|install-node1-desktop)
		from="root@node1:/usr/local/bs/install/"
		to="/home/shared/dev/install/"
		excludefrom+="${install_exclude}"
		;;
	idn2|install-desktop-node2)
		from="/home/shared/dev/install/"
		to="root@node2:/usr/local/bs/install/"
		excludefrom+="${install_exclude}"
		;;
	in2d|install-node2-desktop)
		from="root@node2:/usr/local/bs/install/"
		to="/home/shared/dev/install/"
		excludefrom+="${install_exclude}"
		;;
	# bs
	bdn1|bin-desktop-node1)
		from="/usr/local/bs/"
		to="root@node1:/usr/local/bs/"
		excludefrom+="${exclude_bin}"
		;;
	bn1d|bin-node1-desktop)
		from="root@node1:/usr/local/bs/"
		to="/usr/local/bs/"
		excludefrom+="${exclude_bin}"
		;;
	bdn2|bin-desktop-node2)
		from="/usr/local/bs/"
		to="root@node2:/usr/local/bs/"
		excludefrom+="${exclude_bin}"
		;;
	bn2d|bin-node2-desktop)
		from="root@node2:/usr/local/bs/"
		to="/usr/local/bs/"
		excludefrom+="${exclude_bin}"
		;;
	*)
		_exitE "wrong command: '$1' in '${optsgiven}'"
		;;
esac
shift

# OUT: no command found
[ ! "${cmd}" ] && _echoE "no command found in '${optsgiven}'" && exit 1
# rest options
[ "$*" ] && _echoE "malformed command or too long, rest '$*' in '${optsgiven}'" && exit 1

# call command
eval ${cmd}

_echoD "$FUNCNAME:$LINENO $0 END"
