#!/bin/bash
#
# sync install bs & install path to LXD containers


######################## GLOBAL FUNCTIONS
#S_TRACE=debug

S_GLOBAL_FUNCTIONS="${S_GLOBAL_FUNCTIONS:-/usr/local/bs/inc-functions}"
! . "${S_GLOBAL_FUNCTIONS}" && echo -e "[error] - Unable to source file '${S_GLOBAL_FUNCTIONS}' from '${BASH_SOURCE[0]}'" && exit 1
S_PATH_SCRIPT=${S_PATH_SCRIPT:-/usr/local/bs}
S_PATH_INSTALL=${S_PATH_INSTALL:-/usr/local/install}

########################  VARIABLES

usage="rsync-lxd, sync files between host and LXD containers
rsync-lxd -h, --help

options:
    -h, --help		Print usage of this command
    -v, --verbose		Print details of files transfer
    -p, --create-dirs   Create any directories necessary
    -r, --recursive	Recursively transfer files
    -d, --delete	Delete files before pushing

    --publish		publish container fater sync

    --bs		sync only the path ${S_PATH_SCRIPT}
    --install		sync only the path ${S_PATH_INSTALL}
"

########################  FUNCTION

# check enabled configuration files
__push() {
	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
	local pth pth_sync pth_from pth_tmp ct

	# path
	pths_sel="${pths_sel:-${S_PATH_SCRIPT}}"

	# cts_sel
	cts_sel="${cts_sel:-`lxc list -f csv -c n status=Running`}"

	for pth in ${pths_sel}; do

		pth_sync="${pth//${S_PATH_INSTALL}/\/usr/\local\/install}" # for desktop host
		pth="${pth//-desktop/}" # for desktop host

		pth_from="/tmp/${pth##*/}"
		[ -d "${pth_from}" ] && _eval rm -fR ${pth_from}
		_eval cp -a ${pth} ${pth_from}
		[ -d "${pth_from}/.git" ] && _eval rm -fR "${pth_from}/.git"

		for ct in ${cts_sel}; do
			_echo "${pth} -> ${ct}"

			[ "${delete}" ] && _lxc_exec ${ct} "[ -d "${pth_sync}" ] && rm -fR ${pth_sync}"
			_eval lxc file push ${args} ${pth_from} $ct${pth_sync%/*}
		done
	done
}

__publish() {
	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"
	local ct

	for ct in ${cts_sel}; do
		_echo "publish - ${ct}"
		# rename
		lxc image list -f csv -c l | grep -q ^${ct}$ && _eval lxc image alias rename ${ct} ${ct}-${_SDATE}
		_eval lxc publish --force ${ct} --alias ${ct}
	done
}

__opts() {
	_echod "${FUNCNAME}::${LINENO} IN \$@=$@"

	opts_short="hvrpd"
	opts_long="help,verbose,recursive,create-dirs,delete,publish,bs,install"
	opts=$(getopt -o ${opts_short} -l ${opts_long} -n "${0##*/}" -- "$@") || _exit 1
	eval set -- ${opts}
	_echod "${FUNCNAME}::${LINENO} opts=${*}"

	args=" --quiet"
	while [ "$1" != "--" ]; do
		case "$1" in
			-h|--help)			echo "${usage}" && exit ;;
			-v|--verbose)		args="${args/ --quiet/}"  ;;
			-r|--recursive)		args+=" --recursive"  ;;
			-p|--create-dirs)	args+=" --create-dirs"  ;;
			-d|--delete)			delete=y  ;;
			--publish)			publish=y  ;;
			--bs)						pths_sel+=" ${S_PATH_SCRIPT}"  ;;
			--install)				pths_sel+=" ${S_PATH_INSTALL}"  ;;
		esac
		shift
	done
	shift
	cts_sel=$*
	_echod "${FUNCNAME}::${LINENO} cts_sel=${cts_sel}"
}

__main() {
	_echod "======================================================"
	_echod "$(ps -o args= ${PPID})"
	local opts_short opts_long opts
	local pths_sel args delete cts_sel

	! type lxc >/dev/null 2>&1 && _exite "LXC command not found !"

	__opts "$@"
	__push
	[ "${publish}" ] && __publish
}

########################  MAIN

__main "$@"
