#!/bin/bash
#
# Provides:             vz-clean-files
# Short-Description:    clean files in vz by deleting ortphan files in paths: vz/dump & vz/template
# Description:          clean files in vz by deleting ortphan files in paths: vz/dump & vz/template

################################ GLOBAL FUNCTIONS
#S_TRACE=debug

! [[ "$S_GLOBAL_FUNCTIONS" && -f $S_GLOBAL_FUNCTIONS ]] && echo -e "\e[1;31merror - unable to find file '$S_GLOBAL_FUNCTIONS' from '${BASH_SOURCE[0]}'\e[0;0m" && exit 1
. $S_GLOBAL_FUNCTIONS

################################  MAIN

# openvz server
type vzctl >/dev/null 2>&1 || _exitE "unable to find vzctl command"

_echoD "$_SCRIPT / $(date +"%d-%m-%Y %T : %N") ---- start"


path=$S_VZ_PATH_DUMP

_echoT "clean $path"
for str in $(ls -1 $path/xtra/*.conf| sed "s|.*_\([0-9]\+-[0-9]\+\)\.conf$|\1|"); do
	if ! [ "$(find $path -maxdepth 1 -name "*$str*")" ]; then
		find $path/xtra -name "*$str*"
		find $path/xtra -name "*$str*" -exec rm {} \;
	fi
done


path=$S_VZ_PATH_DUMP_TEMPLATE

_echoT "clean $path"
for str in $(ls -1 $path/xtra/*.conf| sed "s|.*_\([0-9]\+-[0-9]\+\)\.conf$|\1|"); do
	if ! [ "$(find $path -maxdepth 1 -name "*$str*")" ]; then
		find $path/xtra -name "*$str*"
		find $path/xtra -name "*$str*" -exec rm {} \;
	fi
done

