#!/bin/bash
#
# Provides:				vz-dump-all
# Short-Description:	dump all vms, over vzdump
# Description:			dump all vms, over vzdump


# openvz server
type vzctl >/dev/null 2>&1 || _exite "unable to find vzctl command"

! type vzdump >/dev/null 2>&1 && echo "Missing command vzdump" && exit 1

blueb='\e[1;34m'; cclear='\e[0;0m'

echo -e "${blueb}start vzdump for all containers\n$(vzlist -Ho ctid|xargs)${cclear}"

#vz-ctl stop -y all && vz-dump -cy 101-199 && vz-dump -cty 200-254 && vz-ctl start -y all
vz-dump -cfy 101-199

# template
vz-dump -cfty 200-254
